### ISSUE TITLE
maxBuffer error occurs during isolate build.

### ISSUE THREAD

**Issue by jieey1140** [ioi/isolate#130]
I'm going to build the nestjs app as isolate and use it in firebase deploy. 

The following error occurs when executing isolation after nest build.

``` 
file:///Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/isolate-package@1.3.1/node_modules/isolate-package/src/utils/yaml.ts:15
      `Failed to read YAML from ${filePath}: ${getErrorMessage(err)}`
      ^
Error: Error: Error: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at pack (file:///Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/isolate-package@1.3.1/node_modules/isolate-package/src/utils/yaml.ts:15:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at processBuildOutputFiles (file:///Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/isolate-package@1.3.1/node_modules/isolate-package/src/index.ts:76:3)
    at start (file:///Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/isolate-package@1.3.1/node_modules/isolate-package/dist/index.mjs:768:3),[object Promise]
    at process.error (file:///Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/isolate-package@1.3.1/node_modules/isolate-package/src/utils/pack.ts:3:8)
    at process.emit (node:events:527:28)
    at process.emit (/Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
  ```

Which part should I check? 

pnpm 8.6.11 version is in use (macOS)

**Comment by jieey1140** [comment]
I think I posted the wrong issue. I'm sorry!
